package com.iut.banque.test.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TESTLOGINETLOGOUTTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tESTLOGINETLOGOUT() {
    driver.get("http://localhost:8080/_00_ASBank2018_war/");
    driver.manage().window().setSize(new Dimension(770, 816));
    driver.findElement(By.linkText("Page de Login")).click();
    driver.findElement(By.id("controller_Connect_login_action_userCde")).click();
    driver.findElement(By.id("controller_Connect_login_action_userCde")).sendKeys("client1");
    driver.findElement(By.id("controller_Connect_login_action_userPwd")).sendKeys("clientpass1");
    driver.findElement(By.id("controller_Connect_login_action_submit")).click();
    driver.findElement(By.id("logout_Retour")).click();
  }
}
